name: "code"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/code.yaml"
      - ".github/workflows/publish.yaml"
      - "package.json"
      - "lib/**"
      - "README.md"
      - "src/**"
      - "test/*"
      - "tsconfig.json"
      - "tslint.json"
  pull_request:
    paths:
      - ".github/workflows/code.yaml"
      - ".github/workflows/publish.yaml"
      - "package.json"
      - "lib/**"
      - "README.md"
      - "src/**"
      - "test/*"
      - "tsconfig.json"
      - "tslint.json"

jobs:
  test:
    name: lint, test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2.3.4
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Lint code
        run: yarn lint
      - name: Test code
        run: yarn test
      - name: Build code
        run: yarn build
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2.3.4
      - name: Clean old release drafts
        run: hub release -f "%T (%S) %n" --include-drafts | grep " (draft)" | awk '{print $1}' | xargs --no-run-if-empty -t -n1 hub release delete
        env:
          GITHUB_USER: minddocbot
          GITHUB_TOKEN: ${{ secrets.MINDDOCBOT_TOKEN }}
      - name: Create release
        uses: minddocdev/mou-release-action@master
        with:
          draft: true
          prerelease: false
          templatePath: RELEASE_DRAFT/default.md
          token: ${{ secrets.MINDDOCBOT_TOKEN }}
